install: T4262: Fix root partition size for UEFI installs

diff --git a/scripts/install/install-get-partition b/scripts/install/install-get-partition
--- a/scripts/install/install-get-partition
+++ b/scripts/install/install-get-partition
@@ -644,21 +644,29 @@ create_partitions() {
     exit 1
   fi
   if [ -d /sys/firmware/efi ]; then
-       #Need room for the EFI partition.  512 is standard, but 256 is probably okay here
+       ##Do GPT/EFI Setup
+       parted -s /dev/$ldrive mklabel gpt
+       parted --script /dev/$ldrive p >/dev/null 2>&1
+
+       # If we still can't, something has gone terribly wrong
+       if [ "$?" != "0" ]; then
+         echo "Unable to read disk label.  Exiting."
+         exit 1
+       fi
+
        root_part_size=$((root_part_size - 256))
 
-       ##Do GPT/EFI Setup
-       sgdisk --zap-all /dev/$ldrive
        # part1 = BIOS BOOT (backwards compatibility)
        # part2 = EFI
        # part3 = ROOT
-       sgdisk -a1 -n1:34:2047   -t1:EF02 \
-           -n2:2048:+256M -t2:EF00 \
-           -n3:0:0:+$root_part_size -t3:8300 /dev/$ldrive
+       parted --script --align optimal /dev/$ldrive mkpart primary 2048s 4095s
+       parted --script /dev/$ldrive set 1 bios_grub on
+       parted --script --align optimal /dev/$ldrive mkpart primary fat32 4096s 256MiB
+       parted --script /dev/$ldrive set 2 esp on
+       parted --script --align optimal /dev/$ldrive mkpart primary 256MiB $root_part_size
        status=$?
        if [ "$status" != 0 ]; then
           echo -e "Error creating primary partition on $ldrive.\nPlease see $INSTALL_LOG for more details.\nExiting..."
-          lecho "Error creating primary partition on $ldrive.\nparted /dev/$ldrive mkpart primary 0% $root_part_size\n$output"
           exit 1
        fi
        # set the partition number on the device.
